import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Home,FolderOpen,LockKeyhole,Map,Settings,Plus,ArrowRight,Check,Clock3,FileText,Upload,Copy,Download,AlertTriangle,ChevronRight,MessageSquare,ShieldCheck,Languages,X,Trash2,RefreshCw} from "lucide-react";
import "./styles.css";

const seedCase={id:"HAQ-2048",category:"Education",title:"Fee Refund",status:"Response Pending",statement:"Meri university ne kaha tha ke fee refund hogi lekin do mahine se refund nahi diya.",summary:"You state that your university indicated a fee refund would be provided, but you have not received the refund after approximately two months.",facts:["You report having paid a fee.","You state that the university indicated a refund would be provided.","You report contacting the university."],claims:["You believe the refund has not been honored."],missing:["Official refund policy","Written response from the university"],evidence:[{name:"Fee receipt.pdf",type:"PDF",date:"12 May"},{name:"University email",type:"Email",date:"20 May"}],timeline:[["12 May","Fee paid","Payment receipt recorded."],["20 May","Refund indicated","University communication referenced a refund."],["5 June","Refund requested","Written request made."],["20 June","Follow-up sent","Follow-up communication sent." ]],complaint:"Subject: Request for Resolution Regarding Outstanding Fee Refund\n\nDear Sir/Madam,\n\nI am writing regarding an outstanding fee refund associated with my enrollment at the institution.\n\nAccording to my records, I paid the relevant fee and was subsequently informed that the amount would be refunded. Despite follow-up communication, the refund has not yet been received.\n\nI have attached relevant supporting documentation and respectfully request a written response regarding the status of the refund.\n\nSincerely,\n[User Name]",updates:["Complaint prepared","Complaint submitted","Acknowledgment received","Response pending"]};

const demoAnalyze=(text,category)=>({summary:text?`You described a ${category.toLowerCase()} matter. Based only on what you wrote, the main issue is organized below for your review.`:"Tell HAQ what happened so it can organize your account.",facts:text?[text]:[],claims:text?["The user's account describes an unresolved issue."]:[],missing:["Relevant policy or agreement","Written communications","Payment or transaction record"],evidence:["Original receipt or document","Screenshots/messages","Any reference or complaint number"]});

function load(){try{return JSON.parse(localStorage.getItem("haq-v2-cases"))||[seedCase]}catch{return [seedCase]}}
function App(){
 const [cases,setCases]=useState(load),[page,setPage]=useState("home"),[selected,setSelected]=useState(null),[toast,setToast]=useState(""),[lang,setLang]=useState("EN");
 useEffect(()=>localStorage.setItem("haq-v2-cases",JSON.stringify(cases)),[cases]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(t)}},[toast]);
 const openCase=c=>{setSelected(c);setPage("case")};
 const updateCase=(id,patch)=>setCases(cs=>cs.map(c=>c.id===id?{...c,...patch}:c));
 const addCase=c=>{setCases(cs=>[c,...cs]);setSelected(c);setPage("case")};
 return <div className="shell">
  <aside className="side"><div className="logo">HAQ<span>.</span><small>Hear. Document. Act.</small></div>
   <nav>{[[Home,"home","Home"],[FolderOpen,"cases","My Cases"],[LockKeyhole,"evidence","Evidence Locker"],[Map,"map","Justice Map"],[Settings,"settings","Settings"]].map(([I,k,t])=><button className={page===k?"active":""} onClick={()=>setPage(k)} key={k}><I size={18}/><span>{t}</span></button>)}</nav>
   <div className="sideNote"><ShieldCheck size={15}/> Private by default<br/><small>General information, not legal advice.</small></div>
  </aside>
  <main><header><b>{page==="case"?"Case Details":({home:"Home",cases:"My Cases",evidence:"Evidence Locker",map:"Justice Map",settings:"Settings"}[page]||"Start a Case")}</b><button className="lang" onClick={()=>setLang(lang==="EN"?"اردو":"EN")}><Languages size={15}/>{lang}</button></header>
  <div className="content">{page==="home"&&<HomePage cases={cases} start={()=>setPage("wizard")} openCase={openCase}/>}
   {page==="cases"&&<CasesPage cases={cases} start={()=>setPage("wizard")} openCase={openCase}/>}
   {page==="evidence"&&<Evidence cases={cases} updateCase={updateCase} toast={setToast}/>}
   {page==="map"&&<JusticeMap/>}{page==="settings"&&<SettingsPage cases={cases} setCases={setCases} toast={setToast}/>}
   {page==="wizard"&&<Wizard addCase={addCase} back={()=>setPage("home")} toast={setToast}/>}
   {page==="case"&&selected&&<CasePage c={selected} update={p=>{updateCase(selected.id,p);setSelected({...selected,...p})}} toast={setToast}/>}
  </div></main>{toast&&<div className="toast">{toast}</div>}
 </div>
}
function HomePage({cases,start,openCase}){return <><section className="hero"><div><div className="eyebrow">A civic assistance workspace</div><h1>Something unfair<br/><em>happened?</em></h1><p>You don't need to know what to call it. Tell HAQ what happened, and we'll help you organize facts, evidence, options and next steps.</p><button className="primary" onClick={start}>START HERE <ArrowRight size={17}/></button></div><div className="heroAside"><div className="mini"><b>1,284</b><span>cases documented</span></div><div className="mini"><b>743</b><span>complaints prepared</span></div><div className="mini"><b>312</b><span>issues marked resolved</span></div></div></section><div className="sectionHead"><div><h2>Your cases</h2><p>Private to you.</p></div><button className="linkBtn" onClick={()=>document.querySelector("button")}> </button></div><div className="cards">{cases.slice(0,2).map(c=><CaseCard key={c.id} c={c} open={()=>openCase(c)}/>)}</div></>}
function CaseCard({c,open}){return <article className="card"><div className="meta">{c.id} · {c.category}</div><h3>{c.title}</h3><p>{c.summary}</p><span className="badge">{c.status}</span><button className="secondary" onClick={open}>Open case <ChevronRight size={15}/></button></article>}
function CasesPage({cases,start,openCase}){return <><div className="pageHead"><div><h1>My Cases</h1><p>Everything you document, in one place.</p></div><button className="primary dark" onClick={start}><Plus size={17}/> Start Case</button></div><div className="cards">{cases.map(c=><CaseCard key={c.id} c={c} open={()=>openCase(c)}/>)}</div></>}
function Wizard({addCase,back,toast}){const [step,setStep]=useState(0),[category,setCategory]=useState("Education"),[text,setText]=useState(""),[analysis,setAnalysis]=useState(null),[files,setFiles]=useState([]);const steps=["Tell","Understand","Facts","Evidence","Timeline","Options","Complaint","Case"];const next=()=>setStep(s=>Math.min(7,s+1));return <div><div className="pageHead"><div><h1>Start a Case</h1><p>You don't need legal terminology.</p></div><button className="ghost" onClick={back}>Exit</button></div><div className="steps">{steps.map((x,i)=><span className={i===step?"current":i<step?"done":""} key={x}>{i<step?<Check size={12}/>:i+1} {x}</span>)}</div>
 {step===0&&<Panel title="Tell us what happened"><label>Category</label><div className="chips">{["Education","Workplace","Public Services","Consumer","Housing","Other"].map(x=><button className={category===x?"chip selected":"chip"} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><label>Your account</label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Write naturally. English, Urdu or Roman Urdu is okay."/><div className="actions"><button className="primary dark" onClick={()=>{setAnalysis(demoAnalyze(text,category));next()}}>Continue <ArrowRight size={16}/></button></div></Panel>}
 {step===1&&<Panel title="Here's what we understand"><div className="notice">Review before continuing. HAQ does not decide who is right or wrong.</div><p>{analysis?.summary}</p><div className="actions"><button className="secondary" onClick={()=>setStep(0)}>Edit</button><button className="primary dark" onClick={next}>Yes, continue <ArrowRight size={16}/></button></div></Panel>}
 {step===2&&<div className="two"><Panel title="Documented / provided">{(analysis?.facts||[]).map(x=><div className="fact" key={x}><Check size={15}/>{x}</div>)}</Panel><Panel title="Claims & verification">{(analysis?.claims||[]).map(x=><div className="claim" key={x}>Your claim · {x}</div>)}<h4>Still to verify</h4>{(analysis?.missing||[]).map(x=><div className="missing" key={x}>○ {x}</div>)}</Panel><div className="wideActions"><button className="primary dark" onClick={next}>Continue <ArrowRight size={16}/></button></div></div>}
 {step===3&&<Panel title="Evidence"><p className="muted">Add supporting material. Files stay local in this MVP until a secure storage backend is connected.</p><label className="drop"><Upload size={24}/><b>Choose files</b><span>Images, PDFs, documents, screenshots</span><input type="file" multiple onChange={e=>setFiles([...e.target.files])}/></label>{files.map(f=><div className="fileRow" key={f.name}><FileText size={17}/>{f.name}<span>Ready</span></div>)}<div className="actions"><button className="primary dark" onClick={next}>Continue</button></div></Panel>}
 {step===4&&<Panel title="Timeline"><div className="timeline"><div><b>Today</b><span>Your account was recorded in HAQ.</span></div><div><b>Earlier</b><span>Events can be added from your evidence and messages.</span></div></div><div className="actions"><button className="secondary" onClick={()=>toast("Timeline editor is available on the case page.")}>+ Add event</button><button className="primary dark" onClick={next}>Continue</button></div></Panel>}
 {step===5&&<Panel title="Possible next steps"><Option title="Contact the organization" text="Send a clear written request and keep the response."/><Option title="Submit a formal complaint" text="Use the organization's official complaint channel."/><Option title="Find an appropriate authority" text="Identify the relevant official channel for your issue."/><Option title="Seek qualified advice" text="Consider professional advice when appropriate."/><div className="notice">HAQ provides general information and organizational assistance, not legal advice.</div><div className="actions"><button className="primary dark" onClick={next}>Build complaint <ArrowRight size={16}/></button></div></Panel>}
 {step===6&&<Panel title="Formal complaint"><textarea className="complaint" defaultValue={seedCase.complaint}/><div className="actions"><button className="secondary" onClick={()=>navigator.clipboard?.writeText(seedCase.complaint).then(()=>toast("Complaint copied."))}><Copy size={15}/> Copy</button><button className="primary dark" onClick={next}>Save to case</button></div></Panel>}
 {step===7&&<Panel title="Case created"><div className="created"><ShieldCheck size={44}/><h2>HAQ-2048</h2><p>Your case is saved locally and ready to track.</p><span className="badge">Response Pending</span><button className="primary dark" onClick={()=>addCase({...seedCase,id:"HAQ-"+Math.floor(1000+Math.random()*8999),category,title:"Fee Refund",statement:text||seedCase.statement,summary:analysis?.summary||seedCase.summary,facts:analysis?.facts||seedCase.facts,claims:analysis?.claims||seedCase.claims,missing:analysis?.missing||seedCase.missing,evidence:files.map(f=>({name:f.name,type:f.type||"File",date:"Today"})),timeline:seedCase.timeline,complaint:seedCase.complaint,updates:seedCase.updates})}>View My Case</button></div></Panel>}
 </div>}
function Option({title,text}){return <div className="option"><b>{title}</b><span>{text}</span><ChevronRight size={16}/></div>}
function Panel({title,children}){return <section className="panel"><h2>{title}</h2>{children}</section>}
function CasePage({c,update,toast}){const [tab,setTab]=useState("timeline");const [event,setEvent]=useState("");const copy=()=>navigator.clipboard?.writeText(c.complaint).then(()=>toast("Complaint copied."));return <><div className="pageHead"><div><div className="meta">{c.id}</div><h1>{c.category} · {c.title}</h1><p>{c.summary}</p></div><span className="badge">{c.status}</span></div><div className="caseTabs">{["timeline","evidence","complaint","status"].map(t=><button className={tab===t?"selected":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>{tab==="timeline"&&<Panel title="Case timeline"><div className="timeline">{c.timeline.map((e,i)=><div key={i}><b>{e[0]}</b><strong>{e[1]}</strong><span>{e[2]}</span></div>)}</div><div className="inlineAdd"><input value={event} onChange={e=>setEvent(e.target.value)} placeholder="Add a timeline event"/><button className="secondary" onClick={()=>{if(event){update({timeline:[...c.timeline,["Today","New event",event]]});setEvent("");toast("Timeline updated.")}}}>Add</button></div></Panel>}{tab==="evidence"&&<Panel title="Evidence Locker">{c.evidence.length?c.evidence.map(e=><div className="fileRow" key={e.name}><LockKeyhole size={16}/><b>{e.name}</b><span>{e.type} · {e.date}</span></div>):<Empty text="No evidence added yet."/>}</Panel>}{tab==="complaint"&&<Panel title="Formal complaint"><textarea className="complaint" value={c.complaint} onChange={e=>update({complaint:e.target.value})}/><div className="actions"><button className="secondary" onClick={copy}><Copy size={15}/> Copy</button><button className="primary dark" onClick={()=>toast("Complaint saved.")}>Save</button></div></Panel>}{tab==="status"&&<Panel title="Status history">{c.updates.map((u,i)=><div className="statusRow" key={u}><span className={i===c.updates.length-1?"dot active":"dot"}></span><b>{u}</b>{i===c.updates.length-1&&<span className="muted">Current</span>}</div>)}<button className="secondary" onClick={()=>{update({status:"Resolved"});toast("Marked resolved.");}}>Mark as resolved</button></Panel>}<div className="privacy"><ShieldCheck size={18}/><div><b>Private by default</b><span>Your case and evidence are not published to the Justice Map. HAQ does not determine wrongdoing.</span></div></div></>}
function Evidence({cases,updateCase,toast}){const [caseId,setCaseId]=useState(cases[0]?.id),[files,setFiles]=useState([]);const c=cases.find(x=>x.id===caseId)||cases[0];return <><div className="pageHead"><div><h1>Evidence Locker</h1><p>Organize supporting material privately.</p></div></div><Panel title="Add evidence"><select value={caseId} onChange={e=>setCaseId(e.target.value)}>{cases.map(c=><option value={c.id} key={c.id}>{c.id} · {c.title}</option>)}</select><label className="drop"><Upload size={24}/><b>Choose files</b><span>Nothing is uploaded to a server in demo mode.</span><input type="file" multiple onChange={e=>setFiles([...e.target.files])}/></label>{files.map(f=><div className="fileRow" key={f.name}><FileText size={17}/>{f.name}<button className="secondary" onClick={()=>{updateCase(c.id,{evidence:[...c.evidence,{name:f.name,type:f.type||"File",date:"Today"}]});setFiles([]);toast("Evidence added.")}}>Add</button></div>)}</Panel><Panel title="Stored evidence">{c.evidence.map(e=><div className="fileRow" key={e.name}><LockKeyhole size={16}/><b>{e.name}</b><span>{e.type} · {e.date}</span></div>)}</Panel></>}
function JusticeMap(){return <><div className="pageHead"><div><h1>Justice Map</h1><p>Anonymous, aggregated patterns only.</p></div></div><div className="map"><span className="city lhr">Lahore<br/><b>Education · 42</b></span><span className="city isb">Islamabad<br/><b>Public Services · 23</b></span><span className="city khi">Karachi<br/><b>Workplace · 51</b></span><div className="pak">PAKISTAN</div></div><div className="notice"><AlertTriangle size={17}/> The map does not identify people, organizations, or alleged offenders.</div></>}
function SettingsPage({cases,setCases,toast}){return <><div className="pageHead"><div><h1>Settings</h1><p>Privacy and demo controls.</p></div></div><Panel title="Privacy"><div className="setting"><div><b>Evidence visibility</b><span>Private</span></div><ShieldCheck size={19}/></div><div className="setting"><div><b>AI mode</b><span>Demo-safe deterministic analysis</span></div><span className="badge">No API key</span></div></Panel><Panel title="Data"><button className="secondary" onClick={()=>{const blob=new Blob([JSON.stringify(cases,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="haq-cases.json";a.click()}}><Download size={15}/> Export cases</button> <button className="danger" onClick={()=>{setCases([seedCase]);toast("Demo data restored.")}}><RefreshCw size={15}/> Restore demo</button></Panel><Panel title="About HAQ"><p className="muted">HAQ helps users understand, document, act, and track. It is not a substitute for qualified legal advice or an official complaint authority.</p></Panel></>}
function Empty({text}){return <div className="empty">{text}</div>}
createRoot(document.getElementById("root")).render(<App/>);
